### ISSUE TITLE
Module reloading not working

### ISSUE THREAD

**Issue by botic** [grob/httpserver#1]
I updated the code of a module, but there has been no reloading of the module. The response was still the same as before I changed it.

**Comment by grob** [comment]
Module reloading is currently broken because the main app module is required in the [application context](https://github.com/grob/httpserver/blob/master/lib/context/application.js#L22). Fixing this would require a change in [jsgi connector](https://github.com/ringo/ringojs/blob/master/modules/ringo/jsgi/connector.js#L36), but i think i could come up with a backwards compatible change (i.e. making the `appName` optional, so exporting the app function with `module.exports` would be supported too).

**Comment by botic** [comment]
Ahhh thanks! My first thought was going in that direction when I debugged the code yesterday evening. Switching to this modules was quite easy and I'm now looking to drop my `jetty.xml` and using just one single config instead. Merci for your effort!

**Comment by botic** [comment]
Fixed in 7ec877e
